FROM ubuntu:22.04

RUN apt update && apt install -y ca-certificates

WORKDIR /app
COPY slik ./slik   
COPY config.yaml ./config.yaml

# Ensure the binary is executable
RUN chmod +x ./slik

# Use CMD with array syntax
CMD ["./slik", "-config", "./config.yaml"]
