FROM ubuntu:22.04

RUN apt update && apt install -y ca-certificates

WORKDIR /app
COPY slurmabler ./slurmabler
COPY config.yaml ./config.yaml

# Ensure the binary is executable
RUN chmod +x ./slurmabler

# Use CMD with array syntax
CMD ["./slurmabler", "-config", "./config.yaml"]
